New main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,10 +16,12 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install pytest
+        pip install --upgrade pytest
+        
 
     - name: Run pytest
-      run: pytest -v > test_results.txt
+      run: |
+        pytest -v > test_results.txt || echo "Tests failed"
 
     - name: Display scores
       run: |
