Newly updated main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Python application
+name: CI
 
 on:
   push:
@@ -6,24 +6,29 @@ on:
       - main
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install --upgrade pytest
-        
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Run pytest
-      run: |
-        pytest -v > test_results.txt || echo "Tests failed"
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.8
 
-    - name: Display scores
-      run: |
-        echo "Scores for each function:"
-        cat test_results.txt
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          pip install pytest
+
+      - name: Run tests
+        run: |
+         pytest -v > test_results.txt || echo "Tests failed"
+
+      - name: Display scores
+        run: |
+          echo "Scores for each function:"
+          cat test_results.txt
